### ISSUE TITLE
Track map driver position clues

### ISSUE THREAD

**Issue by JJWatMyself** [LapsTimeOFF/F1MV_Better_Map#13]
It would be great to have a visual clue for who is the race leader and who has been lapped. Below, the race leader has a double circle outline, outer circle being same color as the driver and inner circle being yellow (gold). Lapped drivers have a white outline.
![201542590-fb2c3d42-3dc9-4556-b2c8-02513123b414 1](https://user-images.githubusercontent.com/22590445/210186526-3348fa16-32bf-4fe6-aa50-637258c4bdf3.png)

**Comment by LapsTimeOFF** [comment]
I also got the idea to make it blink when the message "Lapped cars are authorized to overtake"

**Comment by JJWatMyself** [comment]
Totally agree. Easier to flash all those lapped cars as every time they do it differently.

**Comment by JJWatMyself** [comment]
Perez, on soft, Last three sectors on perimeter
![image 1](https://user-images.githubusercontent.com/22590445/210189634-e7055841-26aa-4fe2-a1e5-5adb0018ae07.png)

**Comment by LapsTimeOFF** [comment]
> Perez, on soft, Last three sectors on perimeter
> ![image 1](https://user-images.githubusercontent.com/22590445/210189634-e7055841-26aa-4fe2-a1e5-5adb0018ae07.png)

Design to be reviewed, starting to code the bordered drivers

**Comment by LapsTimeOFF** [comment]
[Branch: #13-TrackMapDriverPositionClue](https://github.com/LapsTimeOFF/F1MV_Better_Map/tree/%2313-TrackMapDriverPositionClue)

**Comment by LapsTimeOFF** [comment]
Check #15

**Comment by LapsTimeOFF** [comment]
> Perez, on soft, Last three sectors on perimeter
> ![image 1](https://user-images.githubusercontent.com/22590445/210189634-e7055841-26aa-4fe2-a1e5-5adb0018ae07.png)

Switched to #16
